# Generated by Django 4.2.3 on 2023-08-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_basket_options_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='stripe_product_price_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
